# Generated by Django 5.2 on 2025-06-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('identificationNumber', models.CharField(db_index=True, max_length=50)),
                ('taxNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('accountNumber', models.CharField(max_length=50)),
                ('bankCode', models.CharField(max_length=20)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('CZECHIA', 'Czechia'), ('SLOVAKIA', 'Slovakia')], default='CZECHIA', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(db_index=True, max_length=50)),
                ('issued', models.DateField()),
                ('dueDate', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('vat', models.IntegerField()),
                ('note', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_sold', to='invoices.person')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_bought', to='invoices.person')),
            ],
        ),
    ]
